/**
 * 0711-GitChain: DataAtom Types
 * 
 * THE STANDARD FOR ELECTRICAL INDUSTRY PRODUCT DATA (ETIM)
 * 
 * Every piece of data is an Atom with full provenance.
 * No naked data - always source + citation + timestamp + contributor.
 */

// ============================================================================
// TRUST LEVELS
// ============================================================================

export type TrustLevel = 
  | 'highest'      // 1: Manufacturer original
  | 'high'         // 2: Classification (ETIM, eClass)
  | 'certified'    // 3: Certification bodies (TÜV, CE)
  | 'verified'     // 4: AI + Human verified
  | 'medium'       // 5: AI generated (unverified)
  | 'customer'     // 6: Customer extensions
  | 'generated'    // 7: Builder/tool output
  | 'community';   // 8: Community contributions

export const TRUST_PRIORITY: Record<TrustLevel, number> = {
  highest: 1,
  high: 2,
  certified: 3,
  verified: 4,
  medium: 5,
  customer: 6,
  generated: 7,
  community: 8,
};

// ============================================================================
// SOURCE TYPES
// ============================================================================

export type SourceType =
  | 'manufacturer'        // Original manufacturer data
  | 'classification'      // ETIM, eClass, UNSPSC
  | 'certification'       // TÜV, CE, DPP, energy labels
  | 'ai_verified'         // AI extraction + human verification
  | 'ai_generated'        // AI extraction (unverified)
  | 'customer_extension'  // Customer-added content (Amazon, etc.)
  | 'builder_output'      // Generated by tools/builders
  | 'community';          // User contributions

export const SOURCE_TO_TRUST: Record<SourceType, TrustLevel> = {
  manufacturer: 'highest',
  classification: 'high',
  certification: 'certified',
  ai_verified: 'verified',
  ai_generated: 'medium',
  customer_extension: 'customer',
  builder_output: 'generated',
  community: 'community',
};

// ============================================================================
// DATA ATOM - The smallest unit of data with full provenance
// ============================================================================

export interface DataAtomSource {
  /** Source type determines trust level */
  type: SourceType;
  
  /** Contributor identifier (e.g., "bombas@0711.io", "bosch", "amazon-de") */
  contributor_id: string;
  
  /** Human-readable contributor name */
  contributor_name?: string;
  
  /** Layer this atom belongs to */
  layer_id: string;
}

export interface DataAtomCitation {
  /** Reference to source document (container ID or path) */
  document: string;
  
  /** Page number if applicable */
  page?: number;
  
  /** Section or table reference */
  section?: string;
  
  /** Original text excerpt */
  excerpt?: string;
  
  /** AI confidence score (0.0 - 1.0) */
  confidence: number;
  
  /** Extraction method */
  method?: 'ocr' | 'pdf_parse' | 'table_extraction' | 'nlp' | 'manual';
}

export interface DataAtomVerification {
  /** Who verified this atom */
  verified_by: string;
  
  /** When it was verified */
  verified_at: string;
  
  /** Verification method */
  method: 'human_review' | 'automated' | 'cross_reference' | 'multi_source';
  
  /** Optional notes from verifier */
  notes?: string;
}

export interface DataAtom<T = unknown> {
  /** The actual value */
  value: T;
  
  /** Unit of measurement (if applicable) */
  unit?: string;
  
  /** Language code (for text values) */
  lang?: string;
  
  /** PROVENANCE - REQUIRED */
  source: DataAtomSource;
  
  /** Trust level (derived from source type, can be overridden) */
  trust: TrustLevel;
  
  /** Git commit hash */
  commit: string;
  
  /** Creation timestamp (ISO 8601) */
  created_at: string;
  
  /** Last modification timestamp */
  updated_at?: string;
  
  /** Citation (required for ai_generated, ai_verified) */
  citation?: DataAtomCitation;
  
  /** Verification (upgrades trust from ai_generated to ai_verified) */
  verification?: DataAtomVerification;
  
  /** Previous values (for audit trail within atom) */
  supersedes?: string[];  // Array of previous atom IDs
}

// ============================================================================
// LAYER - A collection of atoms from one contributor
// ============================================================================

export interface ContainerLayer {
  /** Layer identifier (e.g., "001-etim", "002-ai-enrichment") */
  id: string;
  
  /** Human-readable name */
  name: string;
  
  /** Layer type */
  type: SourceType;
  
  /** Who contributed this layer */
  contributor_id: string;
  
  /** Trust level for the entire layer */
  trust_level: TrustLevel;
  
  /** Does this layer require verification? */
  requires_verification: boolean;
  
  /** Git commit that added this layer */
  commit: string;
  
  /** When the layer was added */
  created_at: string;
  
  /** Last update to any atom in this layer */
  updated_at: string;
  
  /** Number of atoms in this layer */
  atom_count: number;
  
  /** Number of verified atoms */
  verified_count: number;
  
  /** Optional description */
  description?: string;
  
  /** Schema version for this layer's data */
  schema_version?: string;
}

// ============================================================================
// CONTRIBUTOR - Entity that adds data to containers
// ============================================================================

export type ContributorRole = 
  | 'manufacturer'
  | 'classifier'
  | 'certifier'
  | 'ai_agent'
  | 'customer'
  | 'builder'
  | 'user';

export interface Contributor {
  /** Unique identifier (e.g., "bombas@0711.io") */
  id: string;
  
  /** Human-readable name */
  name: string;
  
  /** Role/type of contributor */
  role: ContributorRole;
  
  /** Organization (if applicable) */
  organization?: string;
  
  /** Contact email */
  email?: string;
  
  /** Public key for signing (optional) */
  public_key?: string;
  
  /** When this contributor was registered */
  created_at: string;
  
  /** Contributor statistics */
  stats: {
    total_contributions: number;
    verified_contributions: number;
    containers_contributed_to: number;
  };
  
  /** Trust modifiers (can boost or reduce trust) */
  trust_modifier?: number;  // -2 to +2
}

// ============================================================================
// PRODUCT CONTAINER - Specialized container for ETIM products
// ============================================================================

export interface ProductContainerManifest {
  /** Container ID */
  id: string;  // "0711:product:bosch:7736606982"
  
  /** Current version */
  version: number;
  
  /** Container type */
  type: 'product';
  
  /** Creation timestamp */
  created_at: string;
  
  /** Last update timestamp */
  updated_at: string;
  
  /** Product identity (immutable) */
  identity: {
    /** Supplier number (primary identifier) */
    snr: string;
    
    /** Manufacturer namespace */
    manufacturer: string;
    
    /** EAN/GTIN (if available) */
    gtin?: string;
    
    /** Manufacturer article number */
    manufacturer_aid?: string;
  };
  
  /** ETIM classification */
  etim?: {
    /** ETIM class code */
    class_code: string;  // "EC012034"
    
    /** ETIM class name */
    class_name: string;  // "Luft/Wasser-Wärmepumpe"
    
    /** ETIM version */
    version: string;     // "9.0"
    
    /** Number of ETIM features populated */
    feature_count: number;
  };
  
  /** Layers in this container (ordered by creation) */
  layers: ContainerLayer[];
  
  /** Contributors to this container */
  contributors: {
    id: string;
    role: ContributorRole;
    atom_count: number;
    first_contribution: string;
    last_contribution: string;
  }[];
  
  /** Current blockchain anchor */
  anchor?: {
    tx_hash: string;
    block_number: number;
    network: string;
    timestamp: string;
  };
  
  /** Container statistics */
  stats: {
    total_atoms: number;
    verified_atoms: number;
    total_layers: number;
    total_contributors: number;
    total_commits: number;
    total_citations: number;
  };
}

// ============================================================================
// INJECT RESPONSE - What inject() returns
// ============================================================================

export interface InjectOptions {
  /** Response format */
  format?: 'full' | 'values_only' | 'citations_only';
  
  /** Minimum trust level to include */
  trust_min?: TrustLevel;
  
  /** Specific layers to include (default: all) */
  layers?: string[] | '*';
  
  /** Only return verified atoms */
  verified_only?: boolean;
  
  /** Specific fields to include */
  fields?: string[];
  
  /** Include history? */
  include_history?: boolean;
  
  /** Maximum history entries */
  history_limit?: number;
}

export interface InjectResponse<T = Record<string, DataAtom>> {
  /** Container metadata */
  container: {
    id: string;
    version: number;
    type: string;
  };
  
  /** Blockchain verification */
  anchor: {
    verified: boolean;
    tx_hash?: string;
    block_number?: number;
    network?: string;
    timestamp?: string;
  };
  
  /** The actual data (field -> DataAtom) */
  data: T;
  
  /** Which layers were applied */
  layers_applied: string[];
  
  /** Contributor summary */
  contributors: {
    id: string;
    role: ContributorRole;
    atoms: number;
    verified?: number;
  }[];
  
  /** Optional history */
  history?: {
    total_commits: number;
    recent: {
      version: number;
      commit: string;
      author: string;
      message: string;
      timestamp: string;
    }[];
  };
  
  /** Request metadata */
  meta: {
    requested_at: string;
    processing_ms: number;
    cache_hit: boolean;
  };
}

// ============================================================================
// ETIM FEATURE ATOM - Specialized atom for ETIM features
// ============================================================================

export interface EtimFeatureAtom extends DataAtom<string | number | boolean> {
  /** ETIM feature code */
  etim_feature: string;  // "EF000007"
  
  /** ETIM feature name */
  etim_feature_name: string;  // "Nennleistung"
  
  /** ETIM value code (for coded values) */
  etim_value_code?: string;  // "EV000123"
  
  /** ETIM unit code */
  etim_unit?: string;  // "EU570001"
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Create a new DataAtom with required fields
 */
export function createAtom<T>(
  value: T,
  source: DataAtomSource,
  commit: string,
  options?: {
    unit?: string;
    lang?: string;
    citation?: DataAtomCitation;
  }
): DataAtom<T> {
  return {
    value,
    unit: options?.unit,
    lang: options?.lang,
    source,
    trust: SOURCE_TO_TRUST[source.type],
    commit,
    created_at: new Date().toISOString(),
    citation: options?.citation,
  };
}

/**
 * Compare trust levels (returns negative if a < b, positive if a > b)
 */
export function compareTrust(a: TrustLevel, b: TrustLevel): number {
  return TRUST_PRIORITY[a] - TRUST_PRIORITY[b];
}

/**
 * Check if atom meets minimum trust requirement
 */
export function meetsTrustMin(atom: DataAtom, minTrust: TrustLevel): boolean {
  return TRUST_PRIORITY[atom.trust] <= TRUST_PRIORITY[minTrust];
}
